export const GET_ALL_SONGS_ADMIN_REQUEST = "GET_ALL_SONGS_ADMIN_REQUEST";
export const GET_ALL_SONGS_ADMIN_SUCCESS = "GET_ALL_SONGS_ADMIN_SUCCESS";
export const GET_ALL_SONGS_ADMIN_FAIL = "GET_ALL_SONGS_ADMIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
