export const GET_ALL_SONGS_ADMIN_REQUEST = "GET_ALL_SONGS_ADMIN_REQUEST";
export const GET_ALL_SONGS_ADMIN_SUCCESS = "GET_ALL_SONGS_ADMIN_SUCCESS";
export const GET_ALL_SONGS_ADMIN_FAIL = "GET_ALL_SONGS_ADMIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_REQUEST =
  "GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_REQUEST";
export const GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_SUCCESS =
  "GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_SUCCESS";
export const GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_FAIL =
  "GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_FAIL";

export const CREATE_SONG_REQUEST = "CREATE_SONG_REQUEST";
export const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS";
export const CREATE_SONG_FAIL = "CREATE_SONG_FAIL";
