/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

*/
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations ,} = useGLTF('/final.glb')
  const {actions} = useAnimations(animations,group)
  useEffect(()=>{
actions.kick.play()

  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene"  >
        <group name="Armature" rotation={[Math.PI / 1.7, 0, 0]} scale={0.03}  position={[0,-3,0]}   >
          <primitive object={nodes.mixamorigHips}  />
          <skinnedMesh name="Ch03" geometry={nodes.Ch03.geometry} material={materials.Ch03_Body} skeleton={nodes.Ch03.skeleton } />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/final.glb')
